[time]
	tr_duration = 360 #360 #Duration of each trajectory (Hours)
	outstep = 21600 #(Seconds)

[release]
	species_no = 25
	no_particles = 200 #Number of particles at each release point (horizontal grid and height)
	rel_pm_height = 250
	rel_before_minutes = 5
	rel_after_minutes = 5

[height]
	top = 12500
	base = 250
	interval = 500
	# 'md' mixing depth, '2.0' in km without
	#reception = ['md', '2.0', '5.0']

[station]
	name = 'releases2'
	lat = [7.291, 0.135]
	lon = [80.637, 80.637]
	altitude = [500, 0]
