[time]
	rel_before_minutes = 5
	rel_after_minutes = 5
	tr_duration = 24 #360 #Duration of each trajectory (Hours)
	outstep = 21600 #(Seconds)

[height]
	top = 12500
	base = 250
	interval = 500
	rel_pm_height = 250
	species_no = 25
	no_particles = 200 #Number of particles per heigh
	# 'md' mixing depth, '2.0' in km without
	#reception = ['md', '2.0', '5.0']

[station]
	name = 'kandy_5000'
	lat = 7.291
	lon = 80.637
	altitude = 500
