[time]
	tr_duration = 120 #Duration of each trajectory (Hours)
	outstep = 21600 #(Seconds)

[release]
	species_no = 25
	no_particles = 100 #Number of particles at each release point (horizontal grid and height)
	rel_pm_height = 250
	rel_before_minutes = 5
	rel_after_minutes = 5

[height]
	top = 12500
	base = 250
	interval = 500
	# 'md' mixing depth, '2.0' in km without
	#reception = ['md', '2.0', '5.0']

[station]
	name = 'releases4'
	lat = [30, 0, 30, 0]
	lon = [0, 0, 30, 30]
	altitude = [0, 0, 0, 0]
